#include "gestion_IO_scheduler.h"


/*YA ESTAN TODOS LOS SEMAFOROS DECLARADOS E INICIALIZADOS Y EL DOCUMENTO CONECTADO


FALTARIA:
    - HACER LOS HILOS POR CADA IO
    - LLAMAR LOS SEMAFOROS EN CADA CASE
    - REVISAR CORRECTO FUNCIONAMIENTO
*/